"""initial user model added

Revision ID: 576b8dd8c6f4
Revises: 
Create Date: 2022-04-21 01:07:37.995267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576b8dd8c6f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('current_chat_id', sa.Integer(), nullable=False),
    sa.Column('receiving_updates', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
